import type { Metadata, Viewport } from "next";
import { Plus_Jakarta_Sans, Geist_Mono, JetBrains_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/components/providers";
import "./globals.css";

// Named "--font-sans" (not the font's own "--font-plus-jakarta-sans") to
// match the `--font-sans: var(--font-sans)` theme token in globals.css —
// that token had nothing actually providing `--font-sans` before, so
// `font-sans` was silently falling back to the browser default.
const fontSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Scoped to <body> as "--font-mono" — read by the `.font-mono-manifesto`
// class in globals.css for the RUMAH manifesto's Apple-developer-style
// monospace treatment. Note this does NOT affect Tailwind's built-in
// `font-mono` utility elsewhere in the app (time displays, etc.): that
// utility is generated by `@theme inline`, which bakes in a literal
// `var(--font-geist-mono)` reference at build time, so it can't pick up
// a `--font-mono` redefined here.
const monoFont = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Banyuwangi 11",
  description: "Household management app",
  manifest: "/manifest.json",
  icons: {
    icon: "/icon.svg",
    apple: "/apple-touch-icon.png",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Banyuwangi 11",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: "#ffffff",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${monoFont.variable} flex min-h-full flex-col`}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
