-- ============================================================================
-- Phase 86B — co-owners, staff invites, and the end of the 86A safe harbor
-- ============================================================================
-- Two tables the SaaS flow needs before any auth UI exists:
--
--   household_members  which Google accounts may manage which household, so a
--                      couple can share one house rather than one of them
--                      owning it and the other borrowing a login.
--   staff_invites      a token a staff member opens from WhatsApp on their own
--                      phone, which tells the app which tenant they belong to.
--                      Without it a BYOD device has no way to know.
--
-- Neither is read by the app yet; the auth phase wires them up.
-- ============================================================================

create table if not exists household_members (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references households(id) on delete cascade,
  -- Cascades: if the Google account goes, so does its membership. The
  -- household itself survives — it belongs to the other members (and to
  -- households.owner_auth_id, which is `on delete set null` for that reason).
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner',
  created_at timestamptz not null default now(),
  -- One membership per person per house: without this, "invite again" quietly
  -- doubles the row and any per-member logic starts counting twice.
  unique (household_id, user_id)
);

create index if not exists household_members_user_id_idx on household_members(user_id);

create table if not exists staff_invites (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references households(id) on delete cascade,
  -- Unique, so redeeming a token resolves to exactly one household. The value
  -- itself is generated by the app (a secure random string), not here.
  token text not null unique,
  -- Not null on purpose: an invite link that never expires is a permanent key
  -- to the household, forwarded once in WhatsApp and valid forever.
  expires_at timestamptz not null,
  -- Set when redeemed. Null means still open; the auth phase decides whether
  -- a token is single-use or may onboard several phones before it expires.
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists staff_invites_household_id_idx on staff_invites(household_id);

-- ============================================================================
-- RLS — placeholders, as specified, to be replaced in the auth phase
-- ============================================================================
-- These are open to `anon`, which is the key that ships in the public bundle
-- (see rls-policies.sql). Two consequences worth naming before they are
-- inherited as "how it works":
--
--   * anyone holding that key can list every invite token, which is the whole
--     secret behind a magic link. A token should be checked by a
--     security-definer function that takes the token and returns only its
--     household, never by selecting the table.
--   * anyone can insert a household_members row, i.e. add themselves to any
--     household.
--
-- Acceptable only because nothing reads these tables yet and no second tenant
-- exists. They must be replaced with auth.uid()-based policies in the same
-- phase that first reads them.
-- ============================================================================
alter table household_members enable row level security;
alter table staff_invites enable row level security;

drop policy if exists "placeholder_all_household_members" on household_members;
create policy "placeholder_all_household_members" on household_members
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "placeholder_all_staff_invites" on staff_invites;
create policy "placeholder_all_staff_invites" on staff_invites
  for all to anon, authenticated using (true) with check (true);

-- ============================================================================
-- Cleanup — drop the Phase 86A column defaults
-- ============================================================================
-- 086 defaulted household_id to Banyuwangi 11 so that clients written before
-- multi-tenancy kept working. With the app now sending the column on every
-- insert, the default has become a hazard: a second household's rows would
-- silently land in Banyuwangi 11 wherever a caller forgot it. NOT NULL then
-- turns that silent mis-filing into an honest error.
--
-- One live consequence: a phone with the app still open from before the 86A
-- deploy is running a bundle that omits household_id, so its next low-stock
-- report (inventory_alerts) or chore insert now fails until the page is
-- reloaded. There is no service worker, so a reload is all it takes.
-- ============================================================================
alter table task_entities    alter column household_id drop default;
alter table staff_profiles   alter column household_id drop default;
alter table inventory_items  alter column household_id drop default;
alter table household_tasks  alter column household_id drop default;
alter table inventory_alerts alter column household_id drop default;
