-- ============================================================================
-- Phase 89 — co-owner invites
-- ============================================================================
-- The household's second Google account: a partner, a family member, anyone
-- who should see the owner dashboard rather than the staff view.
--
-- Mirrors staff_invites (migrations/087) deliberately — same shape, same
-- single-use rule, same "the token is the secret" posture — but redeems into
-- household_members instead of device_sessions, because a co-owner brings an
-- identity of their own and a staff phone does not.
-- ============================================================================

create table if not exists owner_invites (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references households(id) on delete cascade,
  -- Unique, so a token resolves to exactly one household. Generated by the
  -- app from crypto.getRandomValues, not here.
  token text not null unique,
  -- Not null: an invite that never expires is a permanent key to the
  -- household, pasted once into WhatsApp and valid forever.
  expires_at timestamptz not null,
  used_at timestamptz,
  -- Who generated it. Kept for the audit trail — "who let this person in" is
  -- the first question anyone asks later. Null if that account is deleted.
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists owner_invites_household_id_idx on owner_invites(household_id);

alter table owner_invites enable row level security;

-- Only people already in the household can see or create its invites, and
-- `anon` has no policy at all. No UPDATE or DELETE: an invite is spent by the
-- definer function below, never edited. Revoking one means letting it expire.
drop policy if exists "owner_invites_select_members" on owner_invites;
create policy "owner_invites_select_members" on owner_invites
  for select to authenticated using (
    exists (
      select 1 from household_members m
      where m.household_id = owner_invites.household_id and m.user_id = auth.uid()
    )
  );

drop policy if exists "owner_invites_insert_members" on owner_invites;
create policy "owner_invites_insert_members" on owner_invites
  for insert to authenticated with check (
    exists (
      select 1 from household_members m
      where m.household_id = owner_invites.household_id and m.user_id = auth.uid()
    )
  );

-- ============================================================================
-- use_owner_invite_token — redeeming into membership
-- ============================================================================
-- SECURITY DEFINER because the person redeeming is, by definition, not yet a
-- member: the select policy above would hide the row from them. They must
-- already be signed in with Google, so there is an identity to admit.
--
-- The update is the same statement that reads the row, so two people racing
-- one link cannot both be let in.
-- ============================================================================
create or replace function use_owner_invite_token(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  resolved uuid;
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  update owner_invites
     set used_at = now()
   where token = p_token
     and expires_at > now()
     and used_at is null
  returning household_id into resolved;

  if resolved is null then
    -- One message for "no such token", "expired" and "already used": a caller
    -- probing tokens learns only that this one is no good.
    raise exception 'invalid_or_expired_invite' using errcode = '22023';
  end if;

  -- do nothing, not an error: clicking your own invite twice should land you
  -- in the household, not on an error screen.
  insert into household_members (household_id, user_id, role)
  values (resolved, uid, 'owner')
  on conflict (household_id, user_id) do nothing;

  return resolved;
end;
$$;

grant execute on function use_owner_invite_token(text) to authenticated;
